// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmgRsrmQsisbOTE_iQOLsDXgt2nv7mfM4',
    appId: '1:888995170199:web:d40270244b08e6819ee6d2',
    messagingSenderId: '888995170199',
    projectId: 'inventory-management-sys-ae340',
    authDomain: 'inventory-management-sys-ae340.firebaseapp.com',
    storageBucket: 'inventory-management-sys-ae340.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCde20b6Wq55kaHY380Zo4hVLPunfT6ivc',
    appId: '1:888995170199:android:357969d486ee40659ee6d2',
    messagingSenderId: '888995170199',
    projectId: 'inventory-management-sys-ae340',
    storageBucket: 'inventory-management-sys-ae340.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQDD3xho_Bco4f9Meyn6BfztsVB0lIAus',
    appId: '1:888995170199:ios:4dbf974161b43d889ee6d2',
    messagingSenderId: '888995170199',
    projectId: 'inventory-management-sys-ae340',
    storageBucket: 'inventory-management-sys-ae340.firebasestorage.app',
    iosBundleId: 'com.example.inventoryManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQDD3xho_Bco4f9Meyn6BfztsVB0lIAus',
    appId: '1:888995170199:ios:4dbf974161b43d889ee6d2',
    messagingSenderId: '888995170199',
    projectId: 'inventory-management-sys-ae340',
    storageBucket: 'inventory-management-sys-ae340.firebasestorage.app',
    iosBundleId: 'com.example.inventoryManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmgRsrmQsisbOTE_iQOLsDXgt2nv7mfM4',
    appId: '1:888995170199:web:971aa22669a3be9d9ee6d2',
    messagingSenderId: '888995170199',
    projectId: 'inventory-management-sys-ae340',
    authDomain: 'inventory-management-sys-ae340.firebaseapp.com',
    storageBucket: 'inventory-management-sys-ae340.firebasestorage.app',
  );
}
